Vagrant.configure("2") do |config|
  config.vm.box = "http://file-server/sharefolder/ohara/baseimage/CentOS7.3-BaseVM.box"
  config.vm.hostname = "cloudera-server"
  config.ssh.username = "root"
  config.ssh.password = "vagrant"

  config.vm.network "public_network", ip: "10.1.3.234", netmask: "255.0.0.0", bridge: "enp3s0"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = 2
  end


  config.vm.provision "shell", name: "install postgresql", inline: "yum install  -y https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm"

  config.vm.provision "shell", name: "copy repository file", inline: "cp /vagrant/cloudera-cdh5.repo /etc/yum.repos.d"

  config.vm.provision "shell", name: "clean yum cache", inline: "yum clean all"
  
  config.vm.provision "shell", name: "install cloudera key", inline: "rpm --import https://10.1.3.232/cloudera/RPM-GPG-KEY-cloudera"

  config.vm.provision "shell", name: "install cdh daemon", inline: "yum install -y cloudera-manager-daemons cloudera-manager-agent cloudera-manager-server cloudera-manager-server-db-2"

  config.vm.provision "shell", name: "firewalld false", inline: "systemctl stop firewalld"
 
  config.vm.provision "shell", name: "firewalld disable", inline: "systemctl disable firewalld"  


end
